apiVersion: v1
kind: Service
metadata:
  name: datanet-backend-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: datanet-backend
  ports:
    - port: 8080
      targetPort: 8080
