version: '3.5'

services:
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    ports: ["9000:9000"]

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:1.0.0-cpu-d030521-1ea92e
    ports: ["19530:19530", "19121:19121"]
    volumes: [./server_config.yaml:/var/lib/milvus/conf/server_config.yaml]

  mongodb:
    container_name: mongodb-datanet
    image: mongo
    ports: ["27017:27017"]