apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanet-mongo-express
spec:
  selector:
    matchLabels:
      app: datanet-mongo-express
  template:
    metadata:
      labels:
        app: datanet-mongo-express
    spec:
      containers:
      - name: datanet-mongo-express
        image: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: datanet-mongodb
        resources:
          limits:
            memory: "3Gi"
            cpu: "1"
        ports:
        - containerPort: 8081
