apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanet-milvus
spec:
  selector:
    matchLabels:
      app: datanet-milvus
  replicas: 1
  template:
    metadata:
      labels:
        app: datanet-milvus
    spec:
      containers:
        - name: datanet-etcd
          image: quay.io/coreos/etcd:v3.5.0
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: revision
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
          command: ["etcd"]
          args: [
            "-advertise-client-urls", "http://127.0.0.1:2379",
            "-listen-client-urls", "http://0.0.0.0:2379",
            "--data-dir", "/etcd"
          ]
          ports:
            - containerPort: 2379
          volumeMounts:
            - name: datanet-volume
              mountPath: /etcd
              subPath: etcd-storage
        - name: datanet-milvus
#          image: milvusdb/milvus:v2.0.1
          image: milvusdb/daily-build:master-20220302-27a7875a
          command: ["milvus"]
          args: ["run", "standalone"]
          env:
            - name: ETCD_ENDPOINTS
              value: localhost:2379
            - name: MINIO_ADDRESS
              value: datanet-minio:9000
          ports:
          - containerPort: 19530
          volumeMounts:
            - name: datanet-volume
              mountPath: /var/lib/milvus
              subPath: milvus-storage
      volumes:
        - name: datanet-volume
          persistentVolumeClaim:
            claimName: datanet-volume
