apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanet-milvus
spec:
  selector:
    matchLabels:
      app: datanet-milvus
  replicas: 1
  template:
    metadata:
      labels:
        app: datanet-milvus
    spec:
      containers:
        - name: datanet-milvus
          image: milvusdb/milvus:v2.0.2
          command: ["milvus"]
          args: ["run", "standalone"]
          env:
            - name: ETCD_ENDPOINTS
              value: datanet-etcd:2379
            - name: MINIO_ADDRESS
              value: datanet-minio:9000
          ports:
          - containerPort: 19530
          volumeMounts:
            - name: datanet-volume
              mountPath: /var/lib/milvus
              subPath: milvus-storage
      volumes:
        - name: datanet-volume
          persistentVolumeClaim:
            claimName: datanet-volume
